version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: football_training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/football_training
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm run db:push && npm run db:seed && npm run dev"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    environment:
      - VITE_API_URL=http://localhost:3001

volumes:
  postgres_data: